<?php

use Illuminate\Database\Seeder;

class CongDoanVienSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr=[
            [
                'tc_id' => '',
                'cv_id' => '',
                'lnv_id' => '',
                'mht_id' => '',
                'cdv_ten' => '',
                'cdv_ngaysinh' => '',
                'cdv_gioitinh' => '',
                'cdv_cmnd' => '',
                'cdv_nguyenquan' => '',
                'cdv_diachi' => '',
                'cdv_sdt' => '',
                'cdv_email' => '',
                'cdv_dantoc' => '',
                'cdv_trinhdo' => '',
                'cdv_tongiao' => '',
                'cdv_ngayvaocd' => '',
                'cdv_ngayvaonganh' => '',
                'cdv_trangthai' => '',
                'cdv_hinhanh' => ''  
            ],[
                'tc_id' => '',
                'cv_id' => '',
                'lnv_id' => '',
                'mht_id' => '',
                'cdv_ten' => '',
                'cdv_ngaysinh' => '',
                'cdv_gioitinh' => '',
                'cdv_cmnd' => '',
                'cdv_nguyenquan' => '',
                'cdv_diachi' => '',
                'cdv_sdt' => '',
                'cdv_email' => '',
                'cdv_dantoc' => '',
                'cdv_trinhdo' => '',
                'cdv_tongiao' => '',
                'cdv_ngayvaocd' => '',
                'cdv_ngayvaonganh' => '',
                'cdv_trangthai' => '',
                'cdv_hinhanh' => ''
            ],[
                'tc_id' => '',
                'cv_id' => '',
                'lnv_id' => '',
                'mht_id' => '',
                'cdv_ten' => '',
                'cdv_ngaysinh' => '',
                'cdv_gioitinh' => '',
                'cdv_cmnd' => '',
                'cdv_nguyenquan' => '',
                'cdv_diachi' => '',
                'cdv_sdt' => '',
                'cdv_email' => '',
                'cdv_dantoc' => '',
                'cdv_trinhdo' => '',
                'cdv_tongiao' => '',
                'cdv_ngayvaocd' => '',
                'cdv_ngayvaonganh' => '',
                'cdv_trangthai' => '',
                'cdv_hinhanh' => ''
            ],[
                'tc_id' => '',
                'cv_id' => '',
                'lnv_id' => '',
                'mht_id' => '',
                'cdv_ten' => '',
                'cdv_ngaysinh' => '',
                'cdv_gioitinh' => '',
                'cdv_cmnd' => '',
                'cdv_nguyenquan' => '',
                'cdv_diachi' => '',
                'cdv_sdt' => '',
                'cdv_email' => '',
                'cdv_dantoc' => '',
                'cdv_trinhdo' => '',
                'cdv_tongiao' => '',
                'cdv_ngayvaocd' => '',
                'cdv_ngayvaonganh' => '',
                'cdv_trangthai' => '',
                'cdv_hinhanh' => ''
            ],[
                'tc_id' => '',
                'cv_id' => '',
                'lnv_id' => '',
                'mht_id' => '',
                'cdv_ten' => '',
                'cdv_ngaysinh' => '',
                'cdv_gioitinh' => '',
                'cdv_cmnd' => '',
                'cdv_nguyenquan' => '',
                'cdv_diachi' => '',
                'cdv_sdt' => '',
                'cdv_email' => '',
                'cdv_dantoc' => '',
                'cdv_trinhdo' => '',
                'cdv_tongiao' => '',
                'cdv_ngayvaocd' => '',
                'cdv_ngayvaonganh' => '',
                'cdv_trangthai' => '',
                'cdv_hinhanh' => ''
            ],[
                'tc_id' => '',
                'cv_id' => '',
                'lnv_id' => '',
                'mht_id' => '',
                'cdv_ten' => '',
                'cdv_ngaysinh' => '',
                'cdv_gioitinh' => '',
                'cdv_cmnd' => '',
                'cdv_nguyenquan' => '',
                'cdv_diachi' => '',
                'cdv_sdt' => '',
                'cdv_email' => '',
                'cdv_dantoc' => '',
                'cdv_trinhdo' => '',
                'cdv_tongiao' => '',
                'cdv_ngayvaocd' => '',
                'cdv_ngayvaonganh' => '',
                'cdv_trangthai' => '',
                'cdv_hinhanh' => ''
            ],[
                'tc_id' => '',
                'cv_id' => '',
                'lnv_id' => '',
                'mht_id' => '',
                'cdv_ten' => '',
                'cdv_ngaysinh' => '',
                'cdv_gioitinh' => '',
                'cdv_cmnd' => '',
                'cdv_nguyenquan' => '',
                'cdv_diachi' => '',
                'cdv_sdt' => '',
                'cdv_email' => '',
                'cdv_dantoc' => '',
                'cdv_trinhdo' => '',
                'cdv_tongiao' => '',
                'cdv_ngayvaocd' => '',
                'cdv_ngayvaonganh' => '',
                'cdv_trangthai' => '',
                'cdv_hinhanh' => ''
            ],[
                'tc_id' => '',
                'cv_id' => '',
                'lnv_id' => '',
                'mht_id' => '',
                'cdv_ten' => '',
                'cdv_ngaysinh' => '',
                'cdv_gioitinh' => '',
                'cdv_cmnd' => '',
                'cdv_nguyenquan' => '',
                'cdv_diachi' => '',
                'cdv_sdt' => '',
                'cdv_email' => '',
                'cdv_dantoc' => '',
                'cdv_trinhdo' => '',
                'cdv_tongiao' => '',
                'cdv_ngayvaocd' => '',
                'cdv_ngayvaonganh' => '',
                'cdv_trangthai' => '',
                'cdv_hinhanh' => ''
            ],[
                'tc_id' => '',
                'cv_id' => '',
                'lnv_id' => '',
                'mht_id' => '',
                'cdv_ten' => '',
                'cdv_ngaysinh' => '',
                'cdv_gioitinh' => '',
                'cdv_cmnd' => '',
                'cdv_nguyenquan' => '',
                'cdv_diachi' => '',
                'cdv_sdt' => '',
                'cdv_email' => '',
                'cdv_dantoc' => '',
                'cdv_trinhdo' => '',
                'cdv_tongiao' => '',
                'cdv_ngayvaocd' => '',
                'cdv_ngayvaonganh' => '',
                'cdv_trangthai' => '',
                'cdv_hinhanh' => ''
            ],[
                'tc_id' => '',
                'cv_id' => '',
                'lnv_id' => '',
                'mht_id' => '',
                'cdv_ten' => '',
                'cdv_ngaysinh' => '',
                'cdv_gioitinh' => '',
                'cdv_cmnd' => '',
                'cdv_nguyenquan' => '',
                'cdv_diachi' => '',
                'cdv_sdt' => '',
                'cdv_email' => '',
                'cdv_dantoc' => '',
                'cdv_trinhdo' => '',
                'cdv_tongiao' => '',
                'cdv_ngayvaocd' => '',
                'cdv_ngayvaonganh' => '',
                'cdv_trangthai' => '',
                'cdv_hinhanh' => ''
            ]
        ];
        DB::table('CongDoanVien')->insert($arr);
    }
}
